version: '3'
services:
  frontend:
    build: app/
    ports:
      - "80:80"
    depends_on:
      - api
  api:
    build: .
    expose:
      - "5000"
    environment:
      DATABASE_URL: sqlite:////data/db_data.db
    command: sh -c "flask db upgrade && gunicorn -b :5000 --access-logfile - --error-logfile - api:app"
    volumes:
      - data:/data

volumes:
  data:
