"""add token and expiration_date to authorizarion_codes

Revision ID: 0490bb73558d
Revises: 47f1d728ec56
Create Date: 2019-06-23 13:20:07.039501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0490bb73558d'
down_revision = '47f1d728ec56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authorization_codes', sa.Column('expiration_date', sa.DateTime(), nullable=True))
    op.add_column('authorization_codes', sa.Column('token', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authorization_codes', 'token')
    op.drop_column('authorization_codes', 'expiration_date')
    # ### end Alembic commands ###
