"""surprises table

Revision ID: 0c0ff17efbf6
Revises: bae15e44868a
Create Date: 2019-05-24 15:01:10.999631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c0ff17efbf6'
down_revision = 'bae15e44868a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surprises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=140), nullable=True),
    sa.Column('released', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_surprises_released'), 'surprises', ['released'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_surprises_released'), table_name='surprises')
    op.drop_table('surprises')
    # ### end Alembic commands ###
