"""authorization codes table

Revision ID: bae15e44868a
Revises: 
Create Date: 2019-05-24 14:51:56.971505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bae15e44868a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authorization_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('secret_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('authorization_codes')
    # ### end Alembic commands ###
